// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8qfGTwBBquRqi1RDq7dEam1Vz9pljkcg',
    appId: '1:1025748481290:web:eb0aab5a709945326cf6f3',
    messagingSenderId: '1025748481290',
    projectId: 'twitterclonetute-47f5f',
    authDomain: 'twitterclonetute-47f5f.firebaseapp.com',
    storageBucket: 'twitterclonetute-47f5f.firebasestorage.app',
    measurementId: 'G-K95GTP8PES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ZpCKzqY5J29IhkPfTl34JZUZXUlASow',
    appId: '1:1025748481290:android:2da4355b50601f956cf6f3',
    messagingSenderId: '1025748481290',
    projectId: 'twitterclonetute-47f5f',
    storageBucket: 'twitterclonetute-47f5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYQSNab_PydrKdwQMB5ioNVcsnONAdWcA',
    appId: '1:1025748481290:ios:6fa9934d2c7aab776cf6f3',
    messagingSenderId: '1025748481290',
    projectId: 'twitterclonetute-47f5f',
    storageBucket: 'twitterclonetute-47f5f.firebasestorage.app',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYQSNab_PydrKdwQMB5ioNVcsnONAdWcA',
    appId: '1:1025748481290:ios:6fa9934d2c7aab776cf6f3',
    messagingSenderId: '1025748481290',
    projectId: 'twitterclonetute-47f5f',
    storageBucket: 'twitterclonetute-47f5f.firebasestorage.app',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8qfGTwBBquRqi1RDq7dEam1Vz9pljkcg',
    appId: '1:1025748481290:web:cc13208b6b28901b6cf6f3',
    messagingSenderId: '1025748481290',
    projectId: 'twitterclonetute-47f5f',
    authDomain: 'twitterclonetute-47f5f.firebaseapp.com',
    storageBucket: 'twitterclonetute-47f5f.firebasestorage.app',
    measurementId: 'G-Y3PFF1MM45',
  );
}
